name: laundry_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  midtrans_sdk: ^1.1.0
  intl: ^0.20.2
  pdf: ^3.11.3
  path_provider: ^2.1.5
  printing: ^5.14.2
  google_fonts: ^6.3.2
  permission_handler: ^12.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
flutter_launcher_icons:
  image_path: "assets/images/logo.png" 
  android: true 
  ios: true 
